services:
  e2e:
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations: 
    image: reservations
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth: 
    image: auth
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments: 
    image: payments
    env_file:
      - ../apps/payments/.env
  notifications: 
    image: notifications
    env_file:
      - ../apps/notifications/.env
  mongo:
    image: mongo